# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

react_native_path = '../node_modules/react-native'

target 'rncodepush' do
  platform :ios, '9.0'
  
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Third party deps
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => react_native_path + '/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
  
  pod 'React', :path => react_native_path + '', :subspecs => [
    'Core',
    'tvOS',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => react_native_path + "/ReactCommon/yoga"

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'rncodepushTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rncodepush-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for rncodepush-tvOS

  target 'rncodepush-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
